name: widgetbook_workspace # cannot be named just "widgetbook"
description: A playground to streamline shared_ui with Widgetbook
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  shared_ui:
    path: ../packages/shared_ui
  widgetbook: ^3.7.1

dev_dependencies:
  build_runner: ^2.4.7
  widgetbook_generator: ^3.7.0

flutter:
  uses-material-design: true
