name: widgetbook_workspace # cannot be named just "widgetbook"
description: A playground to streamline shared_ui with Widgetbook
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  flutter:
    sdk: flutter
  shared_ui:
    path: ../packages/shared_ui

  widgetbook: ^3.22.0
  widgetbook_annotation: ^3.11.0

dev_dependencies:
  build_runner: ^2.10.1
  widgetbook_generator: ^3.22.0

flutter:
  uses-material-design: true
