name: widgetbook_workspace # cannot be named just "widgetbook"
description: A playground to streamline shared_ui with Widgetbook
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

dependencies:
  flutter:
    sdk: flutter
  shared_ui:
    path: ../packages/shared_ui
  widgetbook: ^3.20.1
  widgetbook_annotation: ^3.9.0

dev_dependencies:
  build_runner: ^2.10.1
  widgetbook_generator: ^3.20.0

flutter:
  uses-material-design: true
