name: sandbox
description: Widgetbook's own "Widgetbook" (i.e. a catalog for widgets built inside Widgetbook).
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.17.1
  widgetbook_annotation: ^3.7.0

dev_dependencies:
  alchemist: ^0.11.0
  build_runner: ^2.6.0
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^3.17.0

flutter:
  uses-material-design: true
