name: custom_theme_example
description: An example of how to use a custom theme.
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook_annotation: ^3.0.0-beta.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  widgetbook:
    path: ../../packages/widgetbook

flutter:
  uses-material-design: true
