name: admin_app
description: An admin app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  flutter:
    sdk: flutter
  shared_ui:
    path: ../../packages/shared_ui

flutter:
  uses-material-design: true
