name: widgetbook_addon
description: A placeholder for Widgetbook's Add-ons.
version: 3.0.0-beta.0
homepage: https://www.widgetbook.io?utm_source=youtube&utm_medium=link&utm_campaign=widgetbook
repository: https://github.com/widgetbook/widgetbook
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://docs.widgetbook.io

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nested: ^1.0.0
  provider: ^6.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
