name: full_example
description: An example project that demonstrates all Widgetbook features.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.20.1
  widgetbook_annotation: ^3.9.0

dev_dependencies:
  build_runner: ^2.10.1
  widgetbook_generator: ^3.20.0

flutter:
  uses-material-design: true
