name: screen_util_example
description: An example project that demonstrates how to use Widgetbook with the flutter_screenutil package.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  widgetbook: ^3.7.0

dev_dependencies:
  build_runner: ^2.4.4
  widgetbook_generator: ^3.6.0

flutter:
  uses-material-design: true
