name: {{name.snakeCase()}}_widgetbook
description: A Widgetbook for the {{package}} package.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^2.4.1
  widgetbook_annotation: ^2.1.0
  {{package}}:
    path: ../../packages/{{package}}

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  widgetbook_generator: ^2.4.1

flutter:
  uses-material-design: true