name: widgetbook_cli
description: CLI that can publish Widgetbook builds and reviews to Widgetbook Cloud.
version: 3.5.0
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_cli
repository: https://github.com/widgetbook/widgetbook/tree/main/packages/widgetbook_cli
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://docs.widgetbook.io
topics: [widgetbook, storybook, ui, tool, cli]

screenshots:
  - description: "Widgetbook Logo"
    path: assets/logo.png

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  analyzer: ^6.8.0
  archive: ^3.3.0
  args: ^2.3.0
  ci: ^0.1.0
  collection: ^1.15.0
  dio: ^5.6.0
  file: ^7.0.0
  mason_logger: ^0.2.5
  meta: ^1.8.0
  mime: ^1.0.4
  path: ^1.8.2
  platform: ^3.0.0
  pool: ^1.5.1
  process: ^5.0.0
  pub_updater: ^0.4.0
  retry: ^3.1.2
  yaml: ^3.1.2

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.12.1

executables:
  widgetbook: cli_production
  widgetbook_staging: cli_staging
  widgetbook_debug: cli_debug
