name: widgetbook_cli
description: A CLI to interact with Widgetbook Cloud.
version: 3.0.0-beta.18
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_models
repository: https://github.com/widgetbook/widgetbook
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://github.com/widgetbook/widgetbook/tree/main/packages/widgetbook_cli

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.10
  build_version: ^2.1.1
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  lints: ^1.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1
 
dependencies: 
  archive: ^3.3.0
  args: ^2.3.0
  ci: ^0.1.0
  dio: ^4.0.6
  file: ^6.1.2
  freezed_annotation: ^2.0.3
  http_parser: ^4.0.1 
  mason_logger: ">=0.1.3 <0.3.0"
  meta: ^1.8.0
  path: ^1.8.2
  pub_updater: ^0.2.2 
  pubspec: ^2.3.0
  test: ^1.12.1
  version: ^2.0.0
  widgetbook_exception: ^0.0.1-beta.2
  widgetbook_git: ^2.2.0-beta.7
executables:
  widgetbook: cli_production
  widgetbook_staging: cli_staging
  widgetbook_debug: cli_debug