name: widgetbook_annotation
description: A package featuring the annotations used by widgetbook_generator.
version: 3.0.0-beta.4
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_annotation
repository: https://github.com/widgetbook/widgetbook
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://docs.widgetbook.io/widgetbook-annotation/overview

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  widgetbook_models: ^3.0.0-beta.2
dev_dependencies:
  test: ^1.18.2
  very_good_analysis: ^3.0.0
