name: widgetbook_annotation
description: A package featuring the annotations used by widgetbook_generator.
version: 2.0.0-beta
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_annotation
repository: https://github.com/widgetbook/widgetbook
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://github.com/widgetbook/widgetbook/tree/main/packages/widgetbook_annotation

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  widgetbook_models:
    path: ../widgetbook_models

dev_dependencies:
  test: ^1.18.2
  very_good_analysis: ^2.3.0
