name: widgetbook_annotation
description: A package featuring the annotations used by widgetbook_generator.
version: 3.2.0
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_annotation
repository: https://github.com/widgetbook/widgetbook/tree/main/packages/widgetbook_annotation
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://docs.widgetbook.io
topics: [widgetbook, storybook, ui, codegen, build-runner]

screenshots:
  - description: 'Widgetbook Logo'
    path: assets/logo.png

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.24.1
