name: widgetbook_annotation
description: A package featuring the annotations used by widgetbook_generator.
version: 3.9.0
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_annotation
repository: https://github.com/widgetbook/widgetbook/tree/main/packages/widgetbook_annotation
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://docs.widgetbook.io
topics: [widgetbook, storybook, ui, codegen, build-runner]

screenshots:
  - description: Widgetbook Logo
    path: assets/logo.webp

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  test: ^1.24.1
