name: widgetbook
description: A flutter storybook that helps professionals and teams to catalogue their widgets.
version: 3.0.0-beta.14
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook
repository: https://github.com/widgetbook/widgetbook
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://docs.widgetbook.io

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.15.0
  device_frame: ^1.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  meta: ^1.8.0
  nested: ^1.0.0
  widgetbook_core: ^3.0.0-beta.8

dev_dependencies:
  build_runner: ^2.2.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  intl: ^0.18.0
  mocktail: ^0.3.0

flutter:
  assets:
    - assets/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraLight.ttf
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
