name: widgetbook
description: A flutter storybook that helps professionals and teams to catalogue their widgets.
version: 3.0.0-beta.8
homepage: https://www.widgetbook.io?utm_source=youtube&utm_medium=link&utm_campaign=widgetbook
repository: https://github.com/widgetbook/widgetbook
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://docs.widgetbook.io

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.15.0
  device_frame: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  go_router: ^6.0.6
  meta: ^1.8.0
  nested: ^1.0.0
  provider: ^6.0.2
  widgetbook_core: ^3.0.0-beta.5
  widgetbook_models: ^3.0.0-beta.2
dev_dependencies:
  build_runner: ^2.2.0
  flutter_localizations:
    sdk: flutter   
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  intl: ^0.17.0 
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  assets:
    - google_fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: google_fonts/Nunito-Black.ttf
        - asset: google_fonts/Nunito-BlackItalic.ttf
        - asset: google_fonts/Nunito-Bold.ttf
        - asset: google_fonts/Nunito-BoldItalic.ttf
        - asset: google_fonts/Nunito-ExtraBold.ttf
        - asset: google_fonts/Nunito-ExtraBoldItalic.ttf
        - asset: google_fonts/Nunito-ExtraLight.ttf
        - asset: google_fonts/Nunito-ExtraLightItalic.ttf
        - asset: google_fonts/Nunito-Italic.ttf
        - asset: google_fonts/Nunito-Light.ttf
        - asset: google_fonts/Nunito-LightItalic.ttf
        - asset: google_fonts/Nunito-Regular.ttf
        - asset: google_fonts/Nunito-SemiBold.ttf
        - asset: google_fonts/Nunito-SemiBoldItalic.ttf

