name: widgetbook_generator
description: A package to automate setup and maintenance of the widgetbook package by using code generation.
version: 3.20.0
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_generator
repository: https://github.com/widgetbook/widgetbook/tree/main/packages/widgetbook_generator
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://docs.widgetbook.io
topics: [widgetbook, storybook, ui, codegen, build-runner]

screenshots:
  - description: Widgetbook Logo
    path: assets/logo.webp

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  analyzer: ^8.0.0
  build: ^4.0.0
  code_builder: ^4.5.0
  collection: ^1.15.0
  crypto: ^3.0.0
  glob: ^2.0.2
  meta: ^1.7.0
  path: ^1.8.0
  source_gen: ^4.0.0
  widgetbook_annotation: ^3.9.0

dev_dependencies:
  dart_style: ^3.0.0
  test: ^1.21.0
