name: widgetbook_cli

on:
  pull_request:
    paths:
      - packages/widgetbook_cli/**
      - .github/workflows/widgetbook-cli.yaml
      - .github/workflows/_package.yml
  push:
    branches:
      - main
    tags:
      - widgetbook_cli-v[0-9]+.[0-9]+.[0-9]+*

jobs:
  _:
    uses: ./.github/workflows/_package.yml
    with:
      working_directory: packages/widgetbook_cli
      min_flutter_version: 3.32.0
