name: widgetbook

on:
  pull_request:
    paths:
      - packages/widgetbook/**
      - .github/workflows/widgetbook.yaml
      - .github/workflows/_package.yml
  push:
    branches:
      - main
    tags:
      - widgetbook-v[0-9]+.[0-9]+.[0-9]+*

jobs:
  _:
    uses: ./.github/workflows/_package.yml
    with:
      working_directory: packages/widgetbook
      min_flutter_version: 3.32.0
