name: widgetbook_git

on:
  pull_request:
    paths:
      - packages/widgetbook_git/**
      - .github/workflows/widgetbook-git.yaml
  push:
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      working_directory: packages/widgetbook_git
      setup: |
        # Setup dummy Git user
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

        # Melos Bootstrap
        dart pub global activate melos
        melos bootstrap --scope='widgetbook_git'
