name: widgetbook_annotation

on:
  pull_request:
    paths:
      - packages/widgetbook_annotation/**
      - .github/workflows/widgetbook-annotation.yaml
  push:
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      working_directory: packages/widgetbook_annotation
      setup: |
        dart pub global activate melos
        melos bootstrap --scope='widgetbook_annotation'
