on: 
  pull_request:
    paths:
      - "packages/widgetbook_models/**"
      - ".github/workflows/widgetbook-models.yaml"
  push:
    branches:
      - main
name: widgetbook_models
jobs:
  test:
    name: test
    defaults:
      run:
        working-directory: packages/widgetbook_models
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout

    - uses: dart-lang/setup-dart@v1

    - name: Dart version
      run: dart --version

    - name: Enable melos
      run: dart pub global activate melos

    - name: Run Tests
      run: dart test

  code-quality:
    defaults:
      run:
        working-directory: packages/widgetbook_models
    name: code quality
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout

    - uses: dart-lang/setup-dart@v1

    - name: Get packages 
      run: dart pub get
    - name: Run analyze
      run: dart analyze