name: widgetbook_generator

on:
  pull_request:
    paths:
      - packages/widgetbook_generator/**
      - .github/workflows/widgetbook-generator.yaml
      - .github/workflows/_package.yml
  push:
    branches:
      - main
    tags:
      - widgetbook_generator-v[0-9]+.[0-9]+.[0-9]+*

jobs:
  _:
    uses: ./.github/workflows/_package.yml
    with:
      working_directory: packages/widgetbook_generator
      min_flutter_version: 3.32.0
