name: widgetbook_annotation

on:
  pull_request:
    paths:
      - packages/widgetbook_annotation/**
      - .github/workflows/widgetbook-annotation.yaml
      - .github/workflows/_package.yml
  push:
    branches:
      - main
    tags:
      - widgetbook_annotation-v[0-9]+.[0-9]+.[0-9]+*

jobs:
  _:
    uses: ./.github/workflows/_package.yml
    with:
      working_directory: packages/widgetbook_annotation
      min_flutter_version: 3.32.0
